# Generated by Django 4.1.5 on 2023-01-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActualBottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_bottle", models.CharField(max_length=300)),
                (
                    "date_created",
                    models.DateTimeField(verbose_name="date_actual_bottle_added_to_db"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.CharField(max_length=300)),
                (
                    "date_created",
                    models.DateTimeField(verbose_name="date_search_input_by_user"),
                ),
            ],
        ),
    ]
