# Generated by Django 4.1.5 on 2023-01-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actualbottle",
            name="photo_url",
            field=models.CharField(default=None, max_length=300),
        ),
    ]
