# Generated by Django 4.1.5 on 2023-01-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuator", "0002_actualbottle_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualbottle",
            name="photo_url",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
